name: Lint
description: Lint

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: ./.github/workflows/utils/setup-node

    - name: Install dependencies
      uses: ./.github/workflows/modules/install-dependencies

    - name: Prettier
      shell: bash
      run: npm run prettier:fix

    - name: Lint
      shell: bash
      run: npm run lint:fix

    - name: Auto commit
      uses: ./.github/workflows/utils/auto-commit
      with:
        message: 'fix: Lint/Prettier'
